# This file is part of muCommander, https://github.com/e6qu/barebones-commander
#
# muCommander is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# muCommander is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Defines various properties used to configure unit tests.
# Copy this file to ./test.properties and edit it before running tests.

# - Local --------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# True to enable local tests, false to disable them.
dev.barebones.commander.commons.file.protocol.local.LocalFileTest#enabled=true;



# - SFTP ---------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# SFTP tests are skipped unless this property is passed with -D.
dev.barebones.commander.commons.file.protocol.sftp.SFTPFileTest#enabled=false;

# URI of the SFTP folder where temporary test files are created.
# This URI must contain valid credentials.
test_properties.sftp_test.temp_folder=



# - ZIP ----------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# True to enable ZIP tests, false to disable them.
dev.barebones.commander.commons.file.archive.zip.ZipArchiveFileTest#enabled=false;
